Create timedelta w/ hours broken out
Windows hit an error of:
    available_time = timedelta(minutes=calc_minutes())
OverflowError: Python int too large to convert to C int